project:
  number: 1
  title: "Hiivmind Pulse Bug Tracker"

views:
  - number: 1
    name: "Prioritized bugs"
    layout: BOARD_LAYOUT
    filter: ""
  - number: 2
    name: "Triage"
    layout: TABLE_LAYOUT
    filter: "status:\"To triage\""
  - number: 3
    name: "In review"
    layout: TABLE_LAYOUT
    filter: "status:\"In review\""
  - number: 4
    name: "My items"
    layout: TABLE_LAYOUT
    filter: "assignee:@me"
